language: java
sudo: false # faster builds

services:
  - docker


script:
  - mvn install
  - cd jdss.performance.filter.infra/logstash/
  - docker build -t javierdavidsantos/jajas .

after_success:
  - echo "Dog_080207D" | docker login -u "javierdavidsantos" --password-stdin
  - docker push "javierdavidsantos/jajas";