## ==============================================
## BUILDER DOCKERFILE
## ==============================================

FROM docker.elastic.co/logstash/logstash:7.2.0


# Prepare dirs
RUN mkdir -p performance-logs


