version: '3.0'

volumes:
  log:

services:
  #The service used to stock the monitoring records.
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
    container_name: elasticsearch
    hostname: elasticsearch
    networks:
    - performance-net
    ports:
    - "9200:9200"
    environment:
    - discovery.type=single-node

  #The service used to show the results, on graphs tables, pipe charts, etc
  kibana:
    image: docker.elastic.co/kibana/kibana:7.2.0
    container_name: kibana
    hostname: kibana
    networks:
    - performance-net
    ports:
      - "5601:5601"

networks:
  performance-net:
    driver: bridge
    ipam:
      config:
      - subnet: 172.30.0.0/17