version: '3.0'

services:

  # the service use to read and parse the logs files.
  logstash:
    image: javier
    container_name: logstash
    hostname: logstash
    networks:
    - performance-net
    volumes:
    -  log:/usr/share/logstash/performance-logs
