version: '3.0'

services:
  #an example container with an application using the filter
  example-app:
    image: jboss/wildfly
    container_name: example-app
    hostname: example-app
    networks:
    - performance-net
    volumes:
    - log:/opt/jboss/performance-logs
    - ./deployments:/opt/jboss/wildfly/standalone/deployments
    ports:
    - "8080:8080"